name: qr_code_vision
description: A pure Dart package for QR detection, decoding and tracking.
version: 0.0.1
homepage: https://github.com/alessandrodiano/qr_code_vision

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  image: ^3.1.0
  collection: ^1.15.0
  dart_reed_solomon: ^0.1.0+2
  equatable: ^2.0.3

dependency_overrides:
  dart_reed_solomon:
    git: https://github.com/alessandrodiano/reed_solomon.git

dev_dependencies:
  test: ^1.20.1